spring.application.name=03-SB-Redis-App

spring.data.redis.url=redis-14084.c15.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=14084
spring.data.redis.username=default
spring.data.redis.password=k73B6I5fRBGSBOXwigyYA1UuQIZ070Kg